/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author rauly
 */
public class frmAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form frmAdministrador
     */
    public frmAdministrador() {
        this.setContentPane(new utilitario.PanelFondo("/imagenes/fondoadministrador.png"));
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mitEmpleados = new javax.swing.JMenuItem();
        mitVehiculos = new javax.swing.JMenuItem();
        mitPromociones = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mitReporteGenera = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mitSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mantenimiento.png"))); // NOI18N
        jMenu1.setText("Mantenimiento");

        mitEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clientes.png"))); // NOI18N
        mitEmpleados.setText("Gestionar Empleados");
        mitEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitEmpleadosActionPerformed(evt);
            }
        });
        jMenu1.add(mitEmpleados);

        mitVehiculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vehiculos.png"))); // NOI18N
        mitVehiculos.setText("Gestionar Vehículos");
        mitVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitVehiculosActionPerformed(evt);
            }
        });
        jMenu1.add(mitVehiculos);

        mitPromociones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/promociones.png"))); // NOI18N
        mitPromociones.setText("Gestionar Promociones");
        mitPromociones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitPromocionesActionPerformed(evt);
            }
        });
        jMenu1.add(mitPromociones);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reporte.png"))); // NOI18N
        jMenu2.setText("Reportes");

        mitReporteGenera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reporte.png"))); // NOI18N
        mitReporteGenera.setText(" Reporte General");
        mitReporteGenera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitReporteGeneraActionPerformed(evt);
            }
        });
        jMenu2.add(mitReporteGenera);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        jMenu3.setText("Salir");

        mitSalir.setText("Cerrar Sesión");
        mitSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitSalirActionPerformed(evt);
            }
        });
        jMenu3.add(mitSalir);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 261, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mitSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitSalirActionPerformed
        // TODO add your handling code here:                                        
    frmLogin login = new frmLogin();
    login.setVisible(true);
    this.dispose(); // Cerramos el menú
    }//GEN-LAST:event_mitSalirActionPerformed

    private void mitEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitEmpleadosActionPerformed
        // TODO add your handling code here:// Crear y mostrar la ventana de Empleados
    frmGestionEmpleados ventanaEmp = new frmGestionEmpleados();
    ventanaEmp.setVisible(true);
    
    // Opcional: Si quieres que esta ventana quede encima y centrada
    ventanaEmp.setLocationRelativeTo(null);
    }//GEN-LAST:event_mitEmpleadosActionPerformed

    private void mitVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitVehiculosActionPerformed
        // TODO add your handling code here:                                           
    // Abrir la ventana de gestión de autos
    frmGestionVehiculos ventanaAutos = new frmGestionVehiculos();
    ventanaAutos.setVisible(true);
    // Nota: No cerramos (dispose) el menú principal, para poder volver

    }//GEN-LAST:event_mitVehiculosActionPerformed

    private void mitPromocionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitPromocionesActionPerformed
        // TODO add your handling code here:// Crear y mostrar la ventana de Promociones
    frmGestionPromociones ventanaPromo = new frmGestionPromociones();
    ventanaPromo.setVisible(true);
    
    ventanaPromo.setLocationRelativeTo(null);
    }//GEN-LAST:event_mitPromocionesActionPerformed

    private void mitReporteGeneraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitReporteGeneraActionPerformed
        // TODO add your handling code here:
        frmReportesAdmin reporte = new frmReportesAdmin();
    reporte.setVisible(true);
    reporte.setLocationRelativeTo(null);
    }//GEN-LAST:event_mitReporteGeneraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mitEmpleados;
    private javax.swing.JMenuItem mitPromociones;
    private javax.swing.JMenuItem mitReporteGenera;
    private javax.swing.JMenuItem mitSalir;
    private javax.swing.JMenuItem mitVehiculos;
    // End of variables declaration//GEN-END:variables
}
