/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;


/**
 *
 * @author rauly
 */
public class frmProcesarVenta extends javax.swing.JFrame {
    

    /**
     * Creates new form frmProcesarVenta
     */
    public frmProcesarVenta() {
        initComponents();
        listarVehiculosDisponibles(); 
        cargarPromociones();
        listarReservas();
        this.setLocationRelativeTo(null);
    }
    void cargarPromociones() {
        cboPromocion.removeAllItems();
        cboPromocion.addItem("Sin Promocion");
        
        Object[] promos = Principal.gestorPromociones.listar();
        for(int i=0; i < Principal.gestorPromociones.cantidad(); i++) {
            clases.Promocion p = (clases.Promocion) promos[i];
            cboPromocion.addItem(p.getNombre());
        }
    }
    void listarReservas() {
        // 1. Definir los títulos de las columnas
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();
        modelo.addColumn("Cód.");
        modelo.addColumn("Cliente");
        modelo.addColumn("Vehículo");
        modelo.addColumn("Tiempo");

        // 2. Traer datos del Gestor
        Object[] datos = Principal.gestorReservas.listar();

        // 3. Llenar la tabla
        for (int i = 0; i < Principal.gestorReservas.cantidad(); i++) {
            clases.Reserva r = (clases.Reserva) datos[i];
            
            if (r != null) {
                modelo.addRow(new Object[]{
                    r.getCodigo(), // Columna 0: Código
                    r.getCliente().getNombres(), // Columna 1: Nombre del cliente
                    // Columna 2: Marca y Modelo juntos para ahorrar espacio
                    r.getVehiculo().getMarca() + " " + r.getVehiculo().getModelo(), 
                    r.getHorasDuracion() + " hrs" // Columna 3: Tiempo
                });
            }
        }
        
        // 4. Asignar a la tabla visual
        tblReservas.setModel(modelo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnBuscarCliente = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtDniCliente = new javax.swing.JTextField();
        txtNombreCliente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVehiculos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPrecioBase = new javax.swing.JTextField();
        txtDescuento = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        btnCotizarActionPerformed = new javax.swing.JButton();
        btnVender = new javax.swing.JButton();
        btnBoleta = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cboPromocion = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cboMetodoPago = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtMontoPagar = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtHorasReserva = new javax.swing.JTextField();
        btnReservar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblReservas = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("DNI Cliente:");

        btnBuscarCliente.setText("Buscar");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre:");

        txtDniCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDniClienteActionPerformed(evt);
            }
        });

        txtNombreCliente.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDniCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCliente)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(22, Short.MAX_VALUE))
            .addComponent(txtNombreCliente)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDniCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscarCliente)
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        tblVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblVehiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVehiculosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblVehiculos);

        jLabel3.setText("Vehiculos Disponibles:");

        jLabel4.setText("Precio Base:");

        jLabel5.setText("Descuento:");

        jLabel6.setText("TOTAL A PAGAR:");

        txtPrecioBase.setEditable(false);

        txtDescuento.setEditable(false);

        txtTotal.setEditable(false);
        txtTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        btnCotizarActionPerformed.setText("Cotizar");
        btnCotizarActionPerformed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCotizarActionPerformedActionPerformed(evt);
            }
        });

        btnVender.setText("REGISTRAR VENTA");
        btnVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderActionPerformed(evt);
            }
        });

        btnBoleta.setText("Imprimir Boleta");
        btnBoleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBoletaActionPerformed(evt);
            }
        });

        jLabel7.setText("Promocion:");

        cboPromocion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sin Promocion" }));
        cboPromocion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboPromocionActionPerformed(evt);
            }
        });

        jLabel8.setText("Método Pago:");

        cboMetodoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Tarjeta", "Transferencia" }));

        jLabel9.setText("Monto a Pagar:");

        jLabel10.setText("Horas de Reserva:");

        txtHorasReserva.setToolTipText("");
        txtHorasReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHorasReservaActionPerformed(evt);
            }
        });

        btnReservar.setForeground(new java.awt.Color(255, 204, 153));
        btnReservar.setText("Reservar  Vehiculo");
        btnReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservarActionPerformed(evt);
            }
        });

        tblReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cód. Reserva", "Cliente", "Vehículo", "Duración"
            }
        ));
        tblReservas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblReservasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblReservas);

        jLabel11.setText("Lista de Reservas Activas:");

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHorasReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel11)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnReservar))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCotizarActionPerformed)
                            .addComponent(btnLimpiar))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addGap(49, 49, 49)
                                            .addComponent(txtDescuento))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(3, 3, 3)
                                            .addComponent(jLabel6)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(49, 49, 49)
                                        .addComponent(txtPrecioBase, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(31, 31, 31)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboPromocion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cboMetodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnVender)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtMontoPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(48, 48, 48)
                                .addComponent(btnBoleta)))))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtHorasReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReservar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtPrecioBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(cboPromocion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLimpiar))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cboMetodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBoleta)
                            .addComponent(btnCotizarActionPerformed))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtMontoPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnVender)))
                .addGap(223, 390, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDniClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDniClienteActionPerformed

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        // TODO add your handling code here:
        // 1. Capturar DNI
    String dni = txtDniCliente.getText();
    
    if (dni.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Ingrese DNI");
        return;
    }

    // 2. Buscar en el Gestor
    clienteSeleccionado = (clases.Cliente) Principal.gestorClientes.buscar(dni);

    // 3. Mostrar resultado
    if (clienteSeleccionado != null) {
        txtNombreCliente.setText(clienteSeleccionado.getNombres() + " " + clienteSeleccionado.getApellidos());
        txtDniCliente.setEditable(false); // Bloquear para no cambiarlo por error
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Cliente no encontrado. Regístrelo en el menú 'Clientes'.");
        clienteSeleccionado = null;
        txtNombreCliente.setText("");
    }
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void btnCotizarActionPerformedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCotizarActionPerformedActionPerformed
        // TODO add your handling code here:
     // 1. Validaciones básicas
     
        if (clienteSeleccionado == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Busque un cliente primero");
        return;
    }
    // 2. LÓGICA MIXTA PARA EL VEHÍCULO (CAMBIO IMPORTANTE)
    // Escenario A: Si NO hemos seleccionado nada de la reserva...
    if (vehiculoSeleccionado == null) {
        // ... entonces obligamos a seleccionar de la tabla de disponibles
        int fila = tblVehiculos.getSelectedRow();
        if (fila == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un auto de la lista o una reserva.");
            return;
        }
        // Obtenemos el auto de la tabla
        String codigoAuto = tblVehiculos.getValueAt(fila, 0).toString();
        vehiculoSeleccionado = (clases.Vehiculo) Principal.gestorVehiculos.buscar(codigoAuto);
    }
    // Escenario B: Si 'vehiculoSeleccionado' YA TIENE DATOS (porque dimos click en Reserva),
    // el código se salta el 'if' anterior y sigue directo. ¡Magia!

    // 3. Obtener Precio Base (Igual que antes)
    double precio = vehiculoSeleccionado.getPrecioBase();

    // 3. LÓGICA DE PROMOCIÓN (CORREGIDA)
    clases.Promocion promoSeleccionada = null;
    double descuento = 0; 
    
    // Obtenemos lo que dice la cajita
    String textoCombo = cboPromocion.getSelectedItem().toString();

    // Solo buscamos si NO es la opción por defecto
    // Usamos 'contains' para evitar problemas con tildes o espacios
    if (!textoCombo.contains("Sin Promocion")) {
        promoSeleccionada = (clases.Promocion) Principal.gestorPromociones.buscar(textoCombo);
        
        // Si la encontró, calculamos. Si no, sigue siendo 0.
        if (promoSeleccionada != null) {
            descuento = promoSeleccionada.calcularDescuento(precio);
        }
    }

    // 4. Calcular Total
    double total = precio - descuento;

    // 5. Mostrar en pantalla
    txtPrecioBase.setText(String.valueOf(precio));
    txtDescuento.setText(String.valueOf(descuento));
    txtTotal.setText(String.valueOf(total));
    txtMontoPagar.setText(String.valueOf(total)); // Pre-llenar pago

    // 6. Obtener Vendedor (Tu lógica de seguridad)
    clases.Vendedor vendedor;
    if (Principal.empleadoAutenticado instanceof clases.Vendedor) {
        vendedor = (clases.Vendedor) Principal.empleadoAutenticado;
    } else {
        vendedor = new clases.Vendedor("000", "Vendedor", "Default", "v", "1");
    }

    // 7. Crear Cotización
    String codCotizacion = "C-" + System.currentTimeMillis();
    
    // AQUÍ PASAMOS 'null' SI NO HAY PROMO, Y ESTÁ BIEN.
    cotizacionActual = new clases.Cotizacion(codCotizacion, clienteSeleccionado, vendedor, vehiculoSeleccionado, promoSeleccionada);

    javax.swing.JOptionPane.showMessageDialog(this, "Cotización generada. Total: $" + total);
    }//GEN-LAST:event_btnCotizarActionPerformedActionPerformed
    
    private void btnVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderActionPerformed
    // 1. Validaciones previas...
    if (cotizacionActual == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Primero debe COTIZAR.");
        return;
    }
    
    // 2. Capturar datos de pago (NUEVO PARA REQ 7)
    String metodo = cboMetodoPago.getSelectedItem().toString();
    double montoPago = 0;
    
    try {
        montoPago = Double.parseDouble(txtMontoPagar.getText());
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Ingrese un monto válido a pagar");
        return;
    }
    
    // Validar que no pague más de lo que cuesta
    if (montoPago > cotizacionActual.getMontoTotal()) {
        javax.swing.JOptionPane.showMessageDialog(this, "El pago no puede ser mayor al total ($" + cotizacionActual.getMontoTotal() + ")");
        return;
    }

    // 3. Crear la Venta enviando los 4 datos correctos
    String codVenta = "V-" + System.currentTimeMillis();
    
    // ¡AQUÍ ESTÁ LA MAGIA! Pasamos método y monto al constructor
    ventaRealizada = new clases.Venta(codVenta, cotizacionActual, metodo, montoPago);
    
    // 4. Guardar
    Principal.gestorVentas.agregar(ventaRealizada);
    
    // 5. Generar Comprobante
    String boleta = ventaRealizada.generarComprobante();
    javax.swing.JOptionPane.showMessageDialog(this, boleta, "BOLETA DE VENTA", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    
    // 6. Limpiar
    listarVehiculosDisponibles(); 
    limpiarFormulario();
    }//GEN-LAST:event_btnVenderActionPerformed

    private void btnBoletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoletaActionPerformed
        // TODO add your handling code here:
        if (ventaRealizada == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "No hay ninguna venta reciente para imprimir.\nPrimero debe 'Registrar Venta'.");
        return;
    }

    // 2. Obtener el texto del comprobante (Usando el método que ya tienes en la clase Venta)
    String textoBoleta = ventaRealizada.generarComprobante();

    // 3. Crear un área de texto para mostrarlo bonito (Formato Imprimible - Req 8)
    javax.swing.JTextArea areaImpresion = new javax.swing.JTextArea(textoBoleta);
    areaImpresion.setRows(15); // Alto
    areaImpresion.setColumns(40); // Ancho
    areaImpresion.setEditable(false); // Que no se pueda borrar
    areaImpresion.setFont(new java.awt.Font("Monospaced", 0, 12)); // Letra tipo ticket

    // 4. Mostrar en una ventana
    javax.swing.JOptionPane.showMessageDialog(this, new javax.swing.JScrollPane(areaImpresion), "IMPRESIÓN DE COMPROBANTE", javax.swing.JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_btnBoletaActionPerformed

    private void cboPromocionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboPromocionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboPromocionActionPerformed

    private void txtHorasReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHorasReservaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHorasReservaActionPerformed

    private void btnReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservarActionPerformed
        // TODO add your handling code here:
        if (clienteSeleccionado == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un Cliente.");
        return;
    }
    if (tblVehiculos.getSelectedRow() == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un Vehículo de la tabla.");
        return;
    }

    String codigoAuto = tblVehiculos.getValueAt(tblVehiculos.getSelectedRow(), 0).toString();
    clases.Vehiculo autoParaReservar = (clases.Vehiculo) Principal.gestorVehiculos.buscar(codigoAuto);
    
    int horas = 0;
    try {
        horas = Integer.parseInt(txtHorasReserva.getText());
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Ingrese un número válido de horas.");
        return;
    }

    clases.Vendedor vendedor;
    if (Principal.empleadoAutenticado instanceof clases.Vendedor) {
        vendedor = (clases.Vendedor) Principal.empleadoAutenticado;
    } else {
        vendedor = new clases.Vendedor("000", "Vendedor", "Turno", "v", "1");
    }

    String codReserva = "R-" + System.currentTimeMillis();
    
    clases.Reserva nuevaReserva = new clases.Reserva(
            codReserva, 
            autoParaReservar, 
            clienteSeleccionado, 
            vendedor, 
            horas
    );

    Principal.gestorReservas.agregar(nuevaReserva);
    
    autoParaReservar.setEstado("Reservado");

    javax.swing.JOptionPane.showMessageDialog(this, 
            "¡Vehículo RESERVADO con éxito!\n" +
            "Código: " + codReserva + "\n" +
            "Duración: " + horas + " horas.");

    listarVehiculosDisponibles(); 
    listarReservas();
    limpiarFormulario(); 
    }//GEN-LAST:event_btnReservarActionPerformed

    private void tblReservasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblReservasMouseClicked
        // TODO add your handling code here:
    int fila = tblReservas.getSelectedRow();
    if (fila == -1) return;

    String codReserva = tblReservas.getValueAt(fila, 0).toString();

    clases.Reserva reservaEncontrada = (clases.Reserva) Principal.gestorReservas.buscar(codReserva);

    if (reservaEncontrada != null) {
        this.clienteSeleccionado = reservaEncontrada.getCliente();
        this.vehiculoSeleccionado = reservaEncontrada.getVehiculo();
        
        txtDniCliente.setText(clienteSeleccionado.getDni());
        txtNombreCliente.setText(clienteSeleccionado.getNombres() + " " + clienteSeleccionado.getApellidos());
        txtDniCliente.setEditable(false); // Bloqueamos para que no lo cambie
        
        tblVehiculos.clearSelection();
        
        javax.swing.JOptionPane.showMessageDialog(this, "Datos de la reserva cargados. Puede proceder a Cotizar.");
    }
    }//GEN-LAST:event_tblReservasMouseClicked

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarFormulario(); 
    
    txtDniCliente.requestFocus();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void tblVehiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVehiculosMouseClicked
        // TODO add your handling code here:
    int fila = tblVehiculos.getSelectedRow();
    if (fila >= 0) { 
        
        tblReservas.clearSelection();
        
        String codigoAuto = tblVehiculos.getValueAt(fila, 0).toString();
        
        this.vehiculoSeleccionado = (clases.Vehiculo) Principal.gestorVehiculos.buscar(codigoAuto);
    }
    }//GEN-LAST:event_tblVehiculosMouseClicked
    clases.Cliente clienteSeleccionado = null;
    clases.Vehiculo vehiculoSeleccionado = null;
    clases.Cotizacion cotizacionActual = null;
    clases.Venta ventaRealizada = null; 
    void listarVehiculosDisponibles() {
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();
        modelo.addColumn("Código");
        modelo.addColumn("Marca");
        modelo.addColumn("Modelo");
        modelo.addColumn("Precio");
        modelo.addColumn("Tipo");

        Object[] disponibles = Principal.gestorVehiculos.listarDisponibles();
        
        for (Object obj : disponibles) {
            clases.Vehiculo v = (clases.Vehiculo) obj;
            modelo.addRow(new Object[]{
                v.getCodigo(),
                v.getMarca(),
                v.getModelo(),
                v.getPrecioBase(),
                v.getTipo()
            });
        }
        tblVehiculos.setModel(modelo);
    }
    void limpiarFormulario() {
        txtNombreCliente.setText("");
        txtPrecioBase.setText("");
        txtDescuento.setText("");
        txtTotal.setText("");
        
        txtDniCliente.setEditable(true);
        txtDniCliente.setText("");
        
        clienteSeleccionado = null;
        vehiculoSeleccionado = null;
        cotizacionActual = null;
        
        if(cboPromocion != null) cboPromocion.setSelectedIndex(0);
        tblVehiculos.clearSelection();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmProcesarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmProcesarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmProcesarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmProcesarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmProcesarVenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBoleta;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnCotizarActionPerformed;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnReservar;
    private javax.swing.JButton btnVender;
    private javax.swing.JComboBox<String> cboMetodoPago;
    private javax.swing.JComboBox<String> cboPromocion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblReservas;
    private javax.swing.JTable tblVehiculos;
    private javax.swing.JTextField txtDescuento;
    private javax.swing.JTextField txtDniCliente;
    private javax.swing.JTextField txtHorasReserva;
    private javax.swing.JTextField txtMontoPagar;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtPrecioBase;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
