/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;


/**
 *
 * @author rauly
 */
public class frmProcesarVenta extends javax.swing.JFrame {
    

    /**
     * Creates new form frmProcesarVenta
     */
    public frmProcesarVenta() {
        initComponents();
        listarVehiculosDisponibles(); 
        cargarPromociones();
    }
    void cargarPromociones() {
        cboPromocion.removeAllItems();
        cboPromocion.addItem("Sin Promocion");
        
        Object[] promos = Principal.gestorPromociones.listar();
        for(int i=0; i < Principal.gestorPromociones.cantidad(); i++) {
            clases.Promocion p = (clases.Promocion) promos[i];
            cboPromocion.addItem(p.getNombre());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnBuscarCliente = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtDniCliente = new javax.swing.JTextField();
        txtNombreCliente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVehiculos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPrecioBase = new javax.swing.JTextField();
        txtDescuento = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        btnCotizar = new javax.swing.JButton();
        btnVender = new javax.swing.JButton();
        btnBoleta = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cboPromocion = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cboMetodoPago = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtMontoPagar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("DNI Cliente:");

        btnBuscarCliente.setText("Buscar");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre:");

        txtDniCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDniClienteActionPerformed(evt);
            }
        });

        txtNombreCliente.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDniCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCliente)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDniCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscarCliente)
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        tblVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblVehiculos);

        jLabel3.setText("Vehiculos Disponibles:");

        jLabel4.setText("Precio Base:");

        jLabel5.setText("Descuento:");

        jLabel6.setText("TOTAL A PAGAR:");

        txtPrecioBase.setEditable(false);

        txtDescuento.setEditable(false);

        txtTotal.setEditable(false);
        txtTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        btnCotizar.setText("Cotizar");
        btnCotizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCotizarActionPerformed(evt);
            }
        });

        btnVender.setText("REGISTRAR VENTA");
        btnVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderActionPerformed(evt);
            }
        });

        btnBoleta.setText("Imprimir Boleta");
        btnBoleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBoletaActionPerformed(evt);
            }
        });

        jLabel7.setText("Promocion:");

        cboPromocion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sin Promocion" }));
        cboPromocion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboPromocionActionPerformed(evt);
            }
        });

        jLabel8.setText("Método Pago:");

        cboMetodoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Tarjeta", "Transferencia" }));

        jLabel9.setText("Monto a Pagar:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPrecioBase, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(91, 91, 91)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboPromocion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cboMetodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnVender)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtMontoPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(btnCotizar)
                        .addGap(314, 314, 314)
                        .addComponent(btnBoleta)))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtPrecioBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(cboPromocion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCotizar)
                    .addComponent(btnBoleta)
                    .addComponent(jLabel8)
                    .addComponent(cboMetodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtMontoPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVender)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDniClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDniClienteActionPerformed

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        // TODO add your handling code here:
        // 1. Capturar DNI
    String dni = txtDniCliente.getText();
    
    if (dni.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Ingrese DNI");
        return;
    }

    // 2. Buscar en el Gestor
    clienteSeleccionado = (clases.Cliente) Principal.gestorClientes.buscar(dni);

    // 3. Mostrar resultado
    if (clienteSeleccionado != null) {
        txtNombreCliente.setText(clienteSeleccionado.getNombres() + " " + clienteSeleccionado.getApellidos());
        txtDniCliente.setEditable(false); // Bloquear para no cambiarlo por error
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Cliente no encontrado. Regístrelo en el menú 'Clientes'.");
        clienteSeleccionado = null;
        txtNombreCliente.setText("");
    }
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void btnCotizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCotizarActionPerformed
        // TODO add your handling code here:
     // 1. Validaciones básicas
     
        if (clienteSeleccionado == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Busque un cliente primero");
            return;
        }
        if (tblVehiculos.getSelectedRow() == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un auto");
            return;
        }

        // 2. Obtener Auto
        String codigoAuto = tblVehiculos.getValueAt(tblVehiculos.getSelectedRow(), 0).toString();
        vehiculoSeleccionado = (clases.Vehiculo) Principal.gestorVehiculos.buscar(codigoAuto);

        // 3. OBTENER PROMOCIÓN (La parte nueva)
        clases.Promocion promoSeleccionada = null;
        String nombrePromo = cboPromocion.getSelectedItem().toString();
        
        if (!nombrePromo.equals("Sin Promocion")) {
            // Buscamos el objeto promoción real
            promoSeleccionada = (clases.Promocion) Principal.gestorPromociones.buscar(nombrePromo);
        }

        // 4. Calcular precios (Usando el objeto promoción si existe)
        double precio = vehiculoSeleccionado.getPrecioBase();
        double descuento = 0;
        
        if (promoSeleccionada != null) {
            descuento = promoSeleccionada.calcularDescuento(precio);
        }
        
        double total = precio - descuento;

        // 5. Mostrar en pantalla
        txtPrecioBase.setText(String.valueOf(precio));
        txtDescuento.setText(String.valueOf(descuento));
        txtTotal.setText(String.valueOf(total));
        
        txtMontoPagar.setText(String.valueOf(total));

        // 6. Obtener Vendedor (Tu lógica de login)
        clases.Vendedor vendedor;
        if (Principal.empleadoAutenticado instanceof clases.Vendedor) {
            vendedor = (clases.Vendedor) Principal.empleadoAutenticado;
        } else {
            vendedor = new clases.Vendedor("000", "Vendedor", "Default", "v", "1");
        }

        // 7. Generar código único
        String codCotizacion = "C-" + System.currentTimeMillis();

        // 8. CREAR COTIZACIÓN (Ahora pasamos promoSeleccionada, que puede ser null o un objeto)
        cotizacionActual = new clases.Cotizacion(codCotizacion, clienteSeleccionado, vendedor, vehiculoSeleccionado, promoSeleccionada);

        javax.swing.JOptionPane.showMessageDialog(this, "Cotización generada con éxito. Total: $" + total);
    }//GEN-LAST:event_btnCotizarActionPerformed

    private void btnVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderActionPerformed
    // 1. Validaciones previas...
    if (cotizacionActual == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Primero debe COTIZAR.");
        return;
    }
    
    // 2. Capturar datos de pago (NUEVO PARA REQ 7)
    String metodo = cboMetodoPago.getSelectedItem().toString();
    double montoPago = 0;
    
    try {
        montoPago = Double.parseDouble(txtMontoPagar.getText());
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Ingrese un monto válido a pagar");
        return;
    }
    
    // Validar que no pague más de lo que cuesta
    if (montoPago > cotizacionActual.getMontoTotal()) {
        javax.swing.JOptionPane.showMessageDialog(this, "El pago no puede ser mayor al total ($" + cotizacionActual.getMontoTotal() + ")");
        return;
    }

    // 3. Crear la Venta enviando los 4 datos correctos
    String codVenta = "V-" + System.currentTimeMillis();
    
    // ¡AQUÍ ESTÁ LA MAGIA! Pasamos método y monto al constructor
    ventaRealizada = new clases.Venta(codVenta, cotizacionActual, metodo, montoPago);
    
    // 4. Guardar
    Principal.gestorVentas.agregar(ventaRealizada);
    
    // 5. Generar Comprobante
    String boleta = ventaRealizada.generarComprobante();
    javax.swing.JOptionPane.showMessageDialog(this, boleta, "BOLETA DE VENTA", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    
    // 6. Limpiar
    listarVehiculosDisponibles(); 
    limpiarFormulario();
    }//GEN-LAST:event_btnVenderActionPerformed

    private void btnBoletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoletaActionPerformed
        // TODO add your handling code here:
        if (ventaRealizada == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "No hay ninguna venta reciente para imprimir.\nPrimero debe 'Registrar Venta'.");
        return;
    }

    // 2. Obtener el texto del comprobante (Usando el método que ya tienes en la clase Venta)
    String textoBoleta = ventaRealizada.generarComprobante();

    // 3. Crear un área de texto para mostrarlo bonito (Formato Imprimible - Req 8)
    javax.swing.JTextArea areaImpresion = new javax.swing.JTextArea(textoBoleta);
    areaImpresion.setRows(15); // Alto
    areaImpresion.setColumns(40); // Ancho
    areaImpresion.setEditable(false); // Que no se pueda borrar
    areaImpresion.setFont(new java.awt.Font("Monospaced", 0, 12)); // Letra tipo ticket

    // 4. Mostrar en una ventana
    javax.swing.JOptionPane.showMessageDialog(this, new javax.swing.JScrollPane(areaImpresion), "IMPRESIÓN DE COMPROBANTE", javax.swing.JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_btnBoletaActionPerformed

    private void cboPromocionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboPromocionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboPromocionActionPerformed
// Variables globales para guardar qué eligió el vendedor
    clases.Cliente clienteSeleccionado = null;
    clases.Vehiculo vehiculoSeleccionado = null;
    clases.Cotizacion cotizacionActual = null;
    clases.Venta ventaRealizada = null; // Aquí guardaremos la venta para poder imprimirla después
    // Método para llenar la tabla SOLO con autos DISPONIBLES
    void listarVehiculosDisponibles() {
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();
        modelo.addColumn("Código");
        modelo.addColumn("Marca");
        modelo.addColumn("Modelo");
        modelo.addColumn("Precio");
        modelo.addColumn("Tipo");

        // Usamos el método listarDisponibles que creamos en el Arreglo
        Object[] disponibles = Principal.gestorVehiculos.listarDisponibles();
        
        for (Object obj : disponibles) {
            clases.Vehiculo v = (clases.Vehiculo) obj;
            modelo.addRow(new Object[]{
                v.getCodigo(),
                v.getMarca(),
                v.getModelo(),
                v.getPrecioBase(),
                v.getDetalle() // o v.getTipo()
            });
        }
        tblVehiculos.setModel(modelo);
    }
    void limpiarFormulario() {
        // Limpiamos cajas de texto
        txtNombreCliente.setText("");
        txtPrecioBase.setText("");
        txtDescuento.setText("");
        txtTotal.setText("");
        
        // Habilitamos de nuevo la búsqueda
        txtDniCliente.setEditable(true);
        txtDniCliente.setText("");
        
        // Reseteamos variables temporales
        clienteSeleccionado = null;
        vehiculoSeleccionado = null;
        cotizacionActual = null;
        
        // Reseteamos combos y tablas
        if(cboPromocion != null) cboPromocion.setSelectedIndex(0);
        tblVehiculos.clearSelection();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmProcesarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmProcesarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmProcesarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmProcesarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmProcesarVenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBoleta;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnCotizar;
    private javax.swing.JButton btnVender;
    private javax.swing.JComboBox<String> cboMetodoPago;
    private javax.swing.JComboBox<String> cboPromocion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVehiculos;
    private javax.swing.JTextField txtDescuento;
    private javax.swing.JTextField txtDniCliente;
    private javax.swing.JTextField txtMontoPagar;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtPrecioBase;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
