/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author rauly
 */
public class frmReportesAdmin extends javax.swing.JFrame {

    /**
     * Creates new form frmReportesAdmin
     */
    public frmReportesAdmin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnStock = new javax.swing.JButton();
        btnIngresos = new javax.swing.JButton();
        btnVendedores = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnStock.setText("Estado de Vehículos");
        btnStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStockActionPerformed(evt);
            }
        });

        btnIngresos.setText("Ingresos Totales");
        btnIngresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresosActionPerformed(evt);
            }
        });

        btnVendedores.setText("Mejores Vendedores");
        btnVendedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendedoresActionPerformed(evt);
            }
        });

        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane1.setViewportView(txtResultado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnStock)
                        .addGap(53, 53, 53)
                        .addComponent(btnIngresos)
                        .addGap(47, 47, 47)
                        .addComponent(btnVendedores)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStock)
                    .addComponent(btnIngresos)
                    .addComponent(btnVendedores))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStockActionPerformed
        // TODO add your handling code here:
        // 1. Contadores
    int disponibles = 0;
    int vendidos = 0;
    int reservados = 0;
    
    // 2. Recorrer la "Base de Datos" en memoria
    Object[] autos = Principal.gestorVehiculos.listar();
    int total = Principal.gestorVehiculos.cantidad();
    
    for(int i=0; i<total; i++) {
        clases.Vehiculo v = (clases.Vehiculo) autos[i];
        if(v.getEstado().equalsIgnoreCase("Disponible")) disponibles++;
        else if(v.getEstado().equalsIgnoreCase("Vendido")) vendidos++;
        else reservados++;
    }
    
    // 3. Imprimir en el Área de Texto
    txtResultado.setText(""); // Limpiar anterior
    txtResultado.append("=== REPORTE DE STOCK DE VEHÍCULOS ===\n\n");
    txtResultado.append("Total de Vehículos: " + total + "\n");
    txtResultado.append("-----------------------------------\n");
    txtResultado.append(" DISPONIBLES : " + disponibles + "\n");
    txtResultado.append(" VENDIDOS    : " + vendidos + "\n");
    txtResultado.append(" RESERVADOS  : " + reservados + "\n");
        
    }//GEN-LAST:event_btnStockActionPerformed

    private void btnIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresosActionPerformed
        // TODO add your handling code here:
        double sumaTotal = 0;
    
    // 1. Traer las ventas
    Object[] ventas = Principal.gestorVentas.listar();
    int cantidad = Principal.gestorVentas.cantidad();
    
    txtResultado.setText("");
    txtResultado.append("=== REPORTE FINANCIERO ===\n\n");
    
    // 2. Recorrer y sumar
    for(int i=0; i<cantidad; i++) {
        clases.Venta venta = (clases.Venta) ventas[i];
        // Asumiendo que Venta tiene getCotizacion() y Cotizacion tiene getMontoTotal()
        double monto = venta.getCotizacion().getMontoTotal(); 
        sumaTotal += monto;
        
        txtResultado.append(" Venta #" + (i+1) + ": $" + monto + "\n");
    }
    
    txtResultado.append("-----------------------------------\n");
    txtResultado.append(" INGRESOS TOTALES ACUMULADOS: $" + sumaTotal + "\n");
    }//GEN-LAST:event_btnIngresosActionPerformed

    private void btnVendedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendedoresActionPerformed
        // TODO add your handling code here:
        txtResultado.setText("");
    txtResultado.append("=== RENDIMIENTO DE VENDEDORES ===\n\n");
    
    Object[] empleados = Principal.gestorEmpleados.listar();
    int total = Principal.gestorEmpleados.cantidad();
    
    for(int i=0; i<total; i++) {
        clases.Empleado e = (clases.Empleado) empleados[i];
        
        // Solo nos interesan los Vendedores, no los Admins
        if (e instanceof clases.Vendedor) {
            clases.Vendedor v = (clases.Vendedor) e;
            // Necesitas haber creado un getter para ventasRealizadas en la clase Vendedor
            // Si no lo tienes, créalo en clases/Vendedor.java: public int getVentasRealizadas() { return ventasRealizadas; }
            txtResultado.append(" - " + v.getNombres() + " " + v.getApellidos() + "\n");
            // Si tienes el contador en la clase:
            // txtResultado.append("   Ventas: " + v.getVentasRealizadas() + "\n\n");
        }
    }
    }//GEN-LAST:event_btnVendedoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmReportesAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmReportesAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmReportesAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmReportesAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmReportesAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresos;
    private javax.swing.JButton btnStock;
    private javax.swing.JButton btnVendedores;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtResultado;
    // End of variables declaration//GEN-END:variables
}
